### ISSUE TITLE
TravisCIのテストがnpm installの途中でコケてる。

### ISSUE THREAD

**Issue by yagi2** [yagi2/hubot-kotori#8]
そのまま。
どうしよう。

``` bash
$ npm install 
npm WARN package.json kotori@0.0.0 No repository field.
npm http GET https://registry.npmjs.org/hubot
npm http GET https://registry.npmjs.org/hubot-diagnostics/0.0.1
npm http GET https://registry.npmjs.org/hubot-google-images
npm http GET https://registry.npmjs.org/hubot-google-translate
npm http GET https://registry.npmjs.org/hubot-help
npm http GET https://registry.npmjs.org/hubot-heroku-keepalive/0.0.4
npm http GET https://registry.npmjs.org/hubot-maps/0.0.2
npm http GET https://registry.npmjs.org/hubot-pugme
npm http GET https://registry.npmjs.org/hubot-redis-brain/0.0.2
npm http GET https://registry.npmjs.org/hubot-rules
npm http GET https://registry.npmjs.org/hubot-scripts
npm http GET https://registry.npmjs.org/hubot-shipit
npm http GET https://registry.npmjs.org/hubot-slack
npm http GET https://registry.npmjs.org/hubot-youtube
npm http GET https://registry.npmjs.org/coffee-script/1.6.3
npm http GET https://registry.npmjs.org/mocha
npm http GET https://registry.npmjs.org/should
npm http GET https://registry.npmjs.org/sinon
npm http 200 https://registry.npmjs.org/hubot-google-translate
npm ERR! Error: No compatible version found: hubot-google-translate@'^0.1.0'
npm ERR! Valid install targets:
npm ERR! ["0.1.0"]
npm ERR!     at installTargetsError (/home/travis/.nvm/v0.8.28/lib/node_modules/npm/lib/cache.js:719:10)
npm ERR!     at /home/travis/.nvm/v0.8.28/lib/node_modules/npm/lib/cache.js:641:10
npm ERR!     at saved (/home/travis/.nvm/v0.8.28/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:302:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
```

**Comment by yagi2** [comment]
TravisCIでのテスト環境のnpmのバージョンが古いからっぽい。
どっかのタイミングで `npm update -g npm` したらいいっぽい？

**Comment by yagi2** [comment]
http://rcmdnk.github.io/blog/2014/09/08/computer-github-travis/

ココらへん .travis.yml の書き方の参考になる。

**Comment by yagi2** [comment]
f58062324ba45a7fb295cec5b6a5f6fcce5b1f06 でテスト通った。
やっぱりbefore_installにupdate挟んだら行けた。
